# Build the application from source
FROM golang:1.24 AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN go build -o loyalty ./cmd/loyalty/.

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian12 AS build-release-stage
WORKDIR /
COPY --from=build-stage /app/loyalty /usr/local/bin/
USER nonroot:nonroot
ENTRYPOINT ["loyalty"]
