# Build the application from source
FROM golang:1.24 AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN go build -o store ./cmd/store/.

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian12 AS build-release-stage
WORKDIR /
COPY --from=build-stage /app/store /usr/local/bin/
USER nonroot:nonroot
EXPOSE 8000
ENTRYPOINT ["store"]
