# Build the application from source
FROM golang:1.24 AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . ./
RUN go build -o dashboard ./cmd/dashboard/.

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian12 AS build-release-stage
WORKDIR /
COPY --from=build-stage /app/dashboard /usr/local/bin/
USER nonroot:nonroot
ENTRYPOINT ["dashboard"]
